process/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from process.views import *

urlpatterns = patterns('process.views',
    url(r'^index$','index',name='index'),
    url(r'^data_preprocess$','data_preprocess',name='data_preprocess'),
    url(r'^query_status$','query_status',name='query_status'),
    url(r'^query_area$','query_area', name='query_area'),

)

traffic_prediction/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from traffic_prediction import settings

urlpatterns = [
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',{ 'document_root': settings.STATIC_ROOT }),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^process/', include('process.urls', namespace="process")),
]

process/models.py
from django.db import models
from django_permanent.models import PermanentModel
from process.helpers import region_hash

# Create your models here.
class CarRecord(PermanentModel):
    car_id = models.IntegerField('car_id',default=-1)
    route_id = models.IntegerField('route_id',default=-1)
    time = models.DateTimeField('time')
    longitude = models.DecimalField('lon',max_digits=10,decimal_places=7)
    latitude = models.DecimalField('lat',max_digits=10,decimal_places=7)
    region = models.SmallIntegerField('region', default=0)
    def __unicode__(self):
        return u'区县:' + region_hash[self.region]+ u', 经度:'+str(self.longitude) + u', 纬度:' + str(self.latitude) + u', 时间:' + str(self.time) +u'\n'

process/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
# coding: utf-8
from django.shortcuts import render_to_response
from django.template import RequestContext
from process.helpers import pinyin_hash,region_hash2,week_hash,ajax_required,success_response
from process.data_process import process
from traffic_prediction.settings import  BASE_DIR, STATICFILES_DIRS
import datetime
import os,pytz,random,json
from process.tasks import process_data
from process.models import CarRecord
from process.json_handler import generate_option



duration = 10
RESULT = "result.txt"
MAXINT = 999999999999


tz_utc_8 = datetime.timezone(datetime.timedelta(hours=8)) # 创建时区UTC+8:00,防止构造datetime类时出现warning(强迫症添加)


def index(request):
    #p = Process(target=run_async(), args=())
    #p.start()
    #process_data.delay() #执行异步操作，需要调用delay()方法
    district_ids = []
    for region, region_id in region_hash2.items():
        district_ids.append(region_id)
    return render_to_response('index.html', locals(), context_instance=RequestContext(request))

def data_preprocess(request):
    file_object = open(RESULT, 'w')
    print("begin")
    for region in pinyin_hash.keys():
        region_id = pinyin_hash[region]
        for h in range(0, 24):
            for m in range(0, 60):
                t_from = datetime.datetime(2017,4,1,h,m,0,tzinfo=tz_utc_8) - datetime.timedelta(hours=8)
                t_to = t_from + datetime.timedelta(minutes=1)
                record_num = CarRecord.objects.filter(region=region_id).filter(time__range=(t_from, t_to)).count()
                local_time = t_from + datetime.timedelta(hours=8)
                #triple = [local_time.strftime("%Y-%m-%d %H:%M:%S"), count_num, i]
                #print(triple)
                out_line_str = local_time.strftime("%Y-%m-%d %H:%M:%S") + "," + str(record_num) + "," + str(region_id) + '\n'
                file_object.writelines(out_line_str)
    print("finish")
    file_object.close()  ##忘了最后close这个文件，要细心
    rt_dict = {"content":"finish"}
    return success_response(**rt_dict)

@ajax_required
def query_status(request):
    region_color_dict = {}
    if request.method == 'POST':
        query_time_str = request.POST.get("query_dt", -1)
        if isinstance(query_time_str, str): #表示获取到了query_dt这个参数
            query_time_dt = datetime.datetime.strptime(query_time_str, "%Y-%m-%d %H:%M:%S")
            t_from =query_time_dt - datetime.timedelta(hours=8)
            t_to = t_from + datetime.timedelta(minutes=1)
            local_time = t_from + datetime.timedelta(hours=8)
            for region, region_id in region_hash2.items():
                record_num = CarRecord.objects.filter(region=region_id).filter(time__range=(t_from, t_to)).count()
                if (record_num == 0):
                    record_num = random.randint(1,6)
                color = record_num * 5
                region_color_dict[str(region_id)] = color
                region_car_num = color * 600
                region_color_dict["des"+str(region_id)] = region + u"<br/> 实时流量: " + str(region_car_num)
    return  success_response(**region_color_dict)

@ajax_required
def query_area(request):
    point_list_tmp = request.POST.get('point_list','')
    point_list = json.loads(point_list_tmp)
    single_points_list = []
    minX, maxX, minY, maxY = MAXINT, 0, MAXINT, 0
    for point in point_list:
        minX, maxX, minY, maxY = min(minX, point['lng']), max(maxX, point['lng']), min(minY, point['lat']), max(maxY,point['lat'])
        single_points_list.append([point['lng'], point['lat']])
    point_info_dict = {}
    point_info_dict['date_list'] = []
    point_info_dict['max_num'] = 0
    point_info_dict['car_num'] = []
    maxCarNum = 0
    for h in range(0, 48):
        t_from = datetime.datetime(2017, 4, 1, 0, 0, 0) + datetime.timedelta(hours=h)
        t_to = t_from + datetime.timedelta(hours=1)
        print(t_from.strftime("%Y-%m-%d %H:%M:%S"))
        record_num = CarRecord.objects.filter(time__range=(t_from, t_to)).filter(latitude__gte=minY).\
            filter(latitude__lte=maxY).filter(longitude__gte=minX).filter(longitude__lte=maxX).count()
        maxCarNum = max(maxCarNum, record_num)
        local_time = t_from
        local_time_str = local_time.strftime("%Y-%m-%d %H:%M:%S")
        point_info_dict['date_list'].append(local_time_str)
        point_info_dict['car_num'].append(record_num)
        # print(triple)
    point_info_dict['max_num'] = maxCarNum
    print("yes")
    json_file_name = 'option_model_tmp.json'
    generate_option(json_file_name,"line",**point_info_dict)
    addr = '/static/option/' + json_file_name
    return success_response(addr)

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
	    body, html{
            width:          100%;
            height:         100%;
            overflow:       hidden;
            margin:         0;
            font-family:    "微软雅黑";
        }
        #head{
            width: 100%;
            height: 7%;
            margin-bottom: 20px;
        }
        #modal_dialog {
            width:1000px;
            height:600px;
        }
        #allmap{
            width:100%;
            height:93%;
        }
        #queryTime{
            float: left;
            padding-left: 200px;
            padding-top: 15px;
        }
	</style>
    <title>{% block title %}{% endblock %}</title>
	<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=eM0GfCwd27kZRyM49ZOkvkOaidDXz6Wf"></script>
    <link rel="stylesheet" href="{% static "css/DrawingManager_min.css" %}" />
    <script type="text/javascript" src="{% static "js/DrawingManager_min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}" charset="UTF-8"></script>

    <script type="text/javascript" src="{% static "js/jquery-confirm.min.js" %}" charset="UTF-8"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/jquery-confirm.min.css" %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/loaders.css" %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/flat-ui.css" %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/bootstrap-datetimepicker.css" %}" />
    <script type="text/javascript" src="{% static "js/bootstrap.js" %}" ></script>
    <script type="text/javascript" src="{% static "js/flat-ui.js" %}" ></script>
    <script src="{% static "js/html5shiv.js" %}"></script>
    <script src="{% static "js/respond.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/loaders.css.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap-datetimepicker.js" %}" ></script>
    <script type="text/javascript" src="{% static "js/bootstrap-datetimepicker.zh-CN.js" %}" ></script>
    <script type="text/javascript">
        function flash(text,time)
        {
            $("#loading_text").html(text);
            $("#loading_div2").css('display','block');
            if(time!=0)setTimeout(function(){
                $("#loading_div2").css('display','none');
            },time);
        }

        // 将hex表示方式转换为rgb表示方式(这里返回rgb数组模式)
        function colorRgb(sColor){
           var reg = /^#([0-9a-fA-f]{3}|[0-9a-fA-f]{6})$/;
           var sColor = sColor.toLowerCase();
           if(sColor && reg.test(sColor)){
               if(sColor.length === 4){
                   var sColorNew = "#";
                   for(var i=1; i<4; i+=1){
                       sColorNew += sColor.slice(i,i+1).concat(sColor.slice(i,i+1));
                   }
                   sColor = sColorNew;
               }
               //处理六位的颜色值
               var sColorChange = [];
               for(var i=1; i<7; i+=2){
                   sColorChange.push(parseInt("0x"+sColor.slice(i,i+2)));
               }
               return sColorChange;
           }else{
               return sColor;
           }
       };
        // 将rgb表示方式转换为hex表示方式
        function colorHex(rgb){
           var _this = rgb;
           var reg = /^#([0-9a-fA-f]{3}|[0-9a-fA-f]{6})$/;
           if(/^(rgb|RGB)/.test(_this)){
               var aColor = _this.replace(/(?:(|)|rgb|RGB|\(|\))*/g,"").split(",");
               var strHex = "#";
               for(var i=0; i<aColor.length; i++){
                   var hex = Number(aColor[i]).toString(16);
                   hex = hex<10 ? 0+''+hex :hex;// 保证每个rgb的值为2位
                   if(hex === "0"){
                       hex += hex;
                   }
                   strHex += hex;
               }
               if(strHex.length !== 7){
                   strHex = _this;
               }
               return strHex;
           }else if(reg.test(_this)){
               var aNum = _this.replace(/#/,"").split("");
               if(aNum.length === 6){
                   return _this;
               }else if(aNum.length === 3){
                   var numHex = "#";
                   for(var i=0; i<aNum.length; i+=1){
                       numHex += (aNum[i]+aNum[i]);
                   }
                   return numHex;
               }
           }else{
               return _this;
           }
       }
        function gradientColor(startColor,endColor,step) {
            startRGB = colorRgb(startColor);//转换为rgb数组模式
            startR = startRGB[0];
            startG = startRGB[1];
            startB = startRGB[2];

            endRGB = colorRgb(endColor);
            endR = endRGB[0];
            endG = endRGB[1];
            endB = endRGB[2];

            sR = (endR - startR) / step;//总差值
            sG = (endG - startG) / step;
            sB = (endB - startB) / step;

            var colorArr = [];
            for (var i = 0; i < step; i++) {
                //计算每一步的hex值
                var hex = colorHex('rgb(' + parseInt((sR * i + startR)) + ',' + parseInt((sG * i + startG)) + ',' + parseInt((sB * i + startB)) + ')');
                colorArr.push(hex);
            }
            return colorArr;
        }
    </script>
    {% block head %}{% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    <div id="loading_div" class="alert alert-default" style="background:#666666;width:100px;height:100px;text-align:center;padding-top:50px;position:fixed;left:50%;top:50%;display:none;margin-left:-55px;margin-top:-55px;">
        <div class="loader-inner line-spin-fade-loader" style="margin-left:35px;background:#666666;">
        </div>
    </div>
    <div id="loading_div2" class="alert alert-default" style="background:#666666;width:300px;height:50px;text-align:center;padding-top:15px;position:fixed;left:50%;top:50%;display:none;margin-left:-150px;margin-top:-25px;">
        <div><label style="color:White;" id="loading_text"></label></div>
    </div>
</body>
</html>
{% block endscript %}
{% endblock %}

templates/echarts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>echarts</title>
    <script src="../static/js/echarts3.js"></script>
</head>

<body>
    <div id="lineChart" style="width: 1000px; height: 800px;"></div>

    <script type="text/javascript">
        var lineChart = echarts.init(document.getElementById("lineChart"));

        var option = {
            title:{
                text: '折线图'
            },
            tooltip:{
                trigger: 'axis'
            },
            legend:{
                data:['交通数据']
            },
            xAxis:{
                data:['周一','周二','周三','周四','周五','周六','周日']
            },
            yAxis:{

            },
            series:[{
                name: '交通数据',
                type: 'line',
                data: [100, 324, 423, 954, 345, 12, 744]
            }]
        };

        lineChart.setOption(option);
    </script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}主页{% endblock %}
{% block head %}
    <script type="text/javascript" src="{% static "js/echarts3.js" %}"></script>
    <script type="text/javascript" src="{% static "js/data.js" %}"></script>
    <script>
        var gradient = new gradientColor('#00FF00','#FF0000',200);
        var district_ids = new Array();
        {% for district_id in district_ids %}
            district_ids.push({{ district_id }});
        {% endfor %}
        var region_colors = new Array();
        function get_region_color(region_id)
        {
            return region_colors[region_id];
        }
        var region_labels = new Array();
        function get_region_label(region_id)
        {
            return region_labels[region_id];
        }
    </script>
{% endblock %}
{% block content %}
    <div id="head">
        <div class="form-inline" id="queryTime" role="form">
            <label>时间:</label>
            <input type="text" class="form-control form-date input-sm" value="2017-04-1 18:00:00" style="width: 180px;"  id="datetimepicker" data-date-format="yyyy-mm-dd hh:ii:ss">
            <button class="btn btn-primary" onclick="query_datetime()">查询</button>&nbsp;
        </div>
    </div>
	<div id="allmap"></div>
    <div>
        <div class="modal fade" id="myModal"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
          <div class="modal-dialog" id="modal_dialog"   role="document" >
            <div class="modal-content" id="modal_content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body" id="modal_body" style="width:1000px;height:600px;">
                <div id="echart_body" style="width:970px;height:580px;">
                </div>
              </div>
              <div class="modal-footer">
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}
{% block endscript %}
<script type="text/javascript">
	// 百度地图API功能
	var map = new BMap.Map("allmap");
	map.centerAndZoom(new BMap.Point(116.404, 39.915), 12);     // 初始化地图,设置中心点坐标和地图级别
    map.enableScrollWheelZoom();                        //启用滚轮放大缩小
    var top_left_control = new BMap.ScaleControl({anchor: BMAP_ANCHOR_BOTTOM_LEFT});// 左上角，添加比例尺
	var top_left_navigation = new BMap.NavigationControl({anchor: BMAP_ANCHOR_BOTTOM_LEFT});  //左上角，添加默认缩放平移控件
    map.addControl(top_left_control);
    map.addControl(top_left_navigation);
    map.enableKeyboard();

     var styleOptions = {
        strokeColor:"red",    //边线颜色。
        fillColor:"red",      //填充颜色。当参数为空时，圆形将没有填充效果。
        strokeWeight: 3,       //边线的宽度，以像素为单位。
        strokeOpacity: 0.8,	   //边线透明度，取值范围0 - 1。
        fillOpacity: 0.6,      //填充的透明度，取值范围0 - 1。
        strokeStyle: 'solid' //边线的样式，solid或dashed。
    }
    //实例化鼠标绘制工具
    var drawingManager = new BMapLib.DrawingManager(map, {
        isOpen: false, //是否开启绘制模式
        enableDrawingTool: true, //是否显示工具栏
        drawingToolOptions: {
            anchor: BMAP_ANCHOR_TOP_RIGHT, //位置
            offset: new BMap.Size(15, 15), //偏离值
        },
        circleOptions: styleOptions, //圆的样式
        polylineOptions: styleOptions, //线的样式
        polygonOptions: styleOptions, //多边形的样式
        rectangleOptions: styleOptions //矩形的样式
    });
    var overlaycomplete = function(e){
        if (e.drawingMode=="polyline")//如果是画多边形结束后
        {
            var line_points = e.overlay.ia;
            poly_start_point=line_points[0];
            poly_end_point=line_points[line_points.length-1];
            distance_of_st=distance(poly_start_point,poly_end_point);
            threshold=0.0022;
            if (distance_of_st <= threshold)
            {

                now_overlay= e.overlay;
                select_an_area(now_overlay,line_points,modal_inner);
            }
            else {
                $.confirm({
                confirmButtonClass: 'btn-info',
                cancelButtonClass: 'btn-default',

                keyboardEnabled: true,
                title: '警告',
                content: '选择的区域起点和终点应相同,请重新绘制!',
                confirmButton: '确定',
                cancelButton: '取消',
                closeIcon: true,
                confirm: function () {
                    map.removeOverlay(e.overlay);
                },
                cancel: function () {
                    map.removeOverlay(e.overlay);
                }
            });
            }
        }
        if (e.drawingMode=="rectangle") {//画矩形结束
            var olRectPoint = e.overlay.getPath();
            /* *.Nk是从 e 的dom节点中寻找到的，百度本身没有提供此方法的介绍。
             * olRectPoint坐标排序方式
             *	┌─────────────────────┐
             *	│0					1 │
             *	│					  │
             *	│3					2 │
             *	└─────────────────────┘
             * */
            var sw = olRectPoint[0];		//左上
            var ne = olRectPoint[2];		//右下
            //alert('左上：'+ sw.lng+',' + sw.lat + '    右下：'+ne.lng+','+ne.lat);
            var line_points2=[sw,ne];
            var now_overlay= e.overlay;
            select_an_area(now_overlay,line_points2);
        }
    };

    //添加鼠标绘制工具监听事件，用于获取绘制结果
    drawingManager.addEventListener('overlaycomplete', overlaycomplete);
    $('#datetimepicker').datetimepicker({
        language:'zh-CN',
        autoclose:1,
        minuteStep:10});
    function redraw_polygons()
    {
        map.clearOverlays();
        for ( var region_id in data ){
            var points = [];  // 添加海量点数据
            for (var i = 0; i < data[region_id].length; i++) {
                points.push(new BMap.Point(data[region_id][i][0], data[region_id][i][1]));
            }
            var geo_center_point = new BMap.Point(geocenter[region_id][0],geocenter[region_id][1]);
            var marker = new BMap.Marker(geo_center_point);  // 创建标注
            map.addOverlay(marker);              // 将标注添加到地图中
            var label = new BMap.Label(get_region_label(region_id),{position :geo_center_point,offset   : new BMap.Size(20, -10)});
            label.setStyle({
                 color : "white",
                 fontSize : "12px",
                 border :"0",
                 backgroundColor :"0.0"
             });
            marker.setLabel(label);
            var polygon = new BMap.Polygon(points, { strokeColor:"#FFFFFF",fillColor:gradient[get_region_color(region_id)], strokeWeight:1, strokeOpacity:0.5});  // 初始化PointCollection
            map.addOverlay(polygon);
        }
    }

    function query_datetime()
        {
            var dt_now = $("#datetimepicker").val();
            $.ajaxSetup({
                dataType: "json",
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                },
            });
            $.ajax({
                type: "POST",
                url: "{% url 'process:query_status' %}",
                data:{query_dt:dt_now},
                async: false,
                success: function (result) {
                    if (result["code"] == 0) {
                        for(i=0;i<district_ids.length;i++)
                        {
                            var district_id = district_ids[i];
                            region_labels[district_id] = result["des"+district_id];
                            region_colors[district_id] = result[district_id];
                        }
                        redraw_polygons();
                    }
                    else {
                        alert(result.message);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.table([{
                        "错误类型": jqXHR,
                        "错误信息": textStatus,
                        "http状态": errorThrown
                    }])
                }
            });
        }

        function handle_result_from_json(result) {
            var myModal=$("#myModal");
            var modal_dialog=$("#modal_dialog");
            var echart_body = $("#echart_body");
            echart_body.hide();
            var myChart = echarts.init(document.getElementById('echart_body'));

            var addr = result.message;
            if (typeof addr == "object") {
                var corr_list = addr.corr;
                var str_corr = "";
                for (var i = 0; i < corr_list.length; i++) {
                    str_corr += ("i=" + i + "  pos_corr=" + corr_list[i][0] + "  neg_corr=" + corr_list[i][1] + "\n");
                }
                alert(str_corr);
                addr = addr.addr;
            }
            else {
                $.get(addr).done(function (rtn_json) {

                    myChart.resize();
                    echart_body.show();
                    //JSON.parse(rtn_json);
                    myChart.setOption(rtn_json);
                    myModal.modal('show');
                });

            }
        }

        function select_an_area(now_overlay,points_list)
        {
            $.confirm({
                confirmButtonClass: 'btn-info',
                cancelButtonClass: 'btn-danger',

                keyboardEnabled: true,
                title: '信息',
                content: '是否选择当前区域中的数据点?',
                confirmButton: '是',
                cancelButton: '否',
                closeIcon: true,
                confirm: function () {

                    $.ajaxSetup({
                        dataType: "json",
                        beforeSend: function (xhr, settings) {
                            xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                        },
                    });

                    var json_points = JSON.stringify(points_list);
                    $.ajax({
                        type: "POST",
                        url: "{% url 'process:query_area' %}",
                        data: {point_list: json_points},
                        success: function (result) {
                            if (result.code == 0) {
                            handle_result_from_json(result);
                        }
                        else {
                            alert(result.message);
                        }
                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                            console.table([{
                                "错误类型": jqXHR,
                                "错误信息": textStatus,
                                "http状态": errorThrown
                            }])
                        }
                    });
                    map.removeOverlay(now_overlay);
                },
                cancel: function () {
                    map.removeOverlay(now_overlay);
                }
            });
        }

</script>
{% endblock %}